# Generated by Django 2.1.3 on 2018-11-26 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20181121_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='some_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
