# Generated by Django 2.1.3 on 2018-12-04 10:11

from django.db import migrations


def update_some_info(apps, schema_editor):
    Visitor = apps.get_model('visitors', 'Visitor')
    for visitor in Visitor.objects.all():
        visitor.some_info = 'Done'
        visitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20181126_1119'),
    ]

    operations = [
        migrations.RunPython(update_some_info)
    ]
